FROM node:22.14 AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install -g npm@11.6.0
RUN npm ci
COPY . .
RUN npm run lint 
RUN npm run tsc 
RUN npm run test 
RUN npx vite build --mode production

FROM nginx:1.27-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]