import {
    Check,
    CircleUser,
    ClipboardCopy,
    ClockFading,
    Ellipsis,
    EyeIcon,
    EyeOff,
    File,
    FileImage,
    FileText,
    GitCompareArrows,
    HardDriveDownload,
    HeartCrack,
    House,
    LoaderCircle,
    LogOut,
    Send,
    Settings,
    ShieldAlert,
    ShieldMinus,
    Trash,
    UserPlus,
    Users,
    X,
    type LucideProps,
} from "lucide-react";
import { forwardRef } from "react";


export const AppIcons = {
    EyeIcon,
    EyeOff,
    Avatar: CircleUser,
    Send,
    Receive: forwardRef<SVGSVGElement, LucideProps>((props, ref) => (
        <Send transform="rotate(180)" ref={ref} {...props} />
    )),
    Copy: ClipboardCopy,
    Check,
    Loader: forwardRef<SVGSVGElement, LucideProps>((props, ref) => (
        <LoaderCircle {...props} className={"animate-spin " + props.className} ref={ref} />
    )),
    FileIcons: {
        txt: FileText,
        png: FileImage,
        jpg: FileImage,
        jpeg: FileImage,
        unknown: File,
    },
    SaveToDisk: HardDriveDownload,
    Pending: ClockFading,
    ShareId: GitCompareArrows,
    Users,
    AddUsers: UserPlus,
    Home: House,
    Settings,
    Logout: LogOut,
    Close: X,
    Ellipsis,
    Block: ShieldAlert,
    UnBlock: ShieldMinus,
    UnFriend: HeartCrack,
    Delete: Trash,
    Reject: X,
};