@host = localhost:5000

### Signup
POST http://{{host}}/api/v1/auth/signup
Content-Type: application/json

{
  "name": "test",
  "email": "test1@test.com",
  "password": "Test@123",
  "confirmPassword": "Test@123"
}

### Login
POST http://{{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "Test@123"
}

### Logout
GET http://{{host}}/api/v1/auth/logout

### Logout
GET http://{{host}}/api/v1/auth/refresh-token
Cookie: refreshToken:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI0YzE4NjExNTAzNjNiNTI4Nzk2ODUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3NTM5NDcwMDcsImV4cCI6MTc1NDU1MTgwN30.jYmzk2Ed5YPvKP9c-IRESUYpu9157hccFQ2-NuiBDy4