@host = localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI0YzE4NjExNTAzNjNiNTI4Nzk2ODUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3NTQwNDIyMjUsImV4cCI6MTc1NDA0MzEyNX0.zbrLffW8B9teGybqaalq72jD21a_Htcich1hnBi8lz4

### Send
POST http://{{host}}/api/v1/friend/request/send
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "receiverEmail": "test1@test.com"
}
