name: Deploy Pipeline

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]
  workflow_dispatch:

jobs:
  all-ci-cd:
    name: Lint, Tests, Build any Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Checkout to Branch
        uses: actions/checkout@v3

      - name: Checkout to Branch
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Backend CI
        run: |
          cd backend
          npm ci

          # This creates the development env for testing 
          cat <<EOF > .env.development
          NODE_ENV=development
          PORT=5000
          HOST=localhost
          MONGO_URI=mongodb://localhost:27017/dev-file-share-v1
          JWT_SECRET=1bc0469f4bc544c6ed0c255fb118b71a063eec520122f6ae7e97ff502a5779455c1caa4af768e752f4fbfb88fef4f60037de6265521963b64daecb7fa3d42d37
          COOKIE_SIGN_SECRET = 17b932dd009a9c7c0eeb85b31513976f16d94a87f7f8e04d58cbc75e2aaa72fb01162eccb671cf426c09c4aab2412f9276862fccc04f50b95e4988aa34b0ee0d
          COOKIE_CRYPTO_SECRET = 67acc8fe5eeae253c575dd14c3b56868a1c8ead0021f4ae8e8286a580287999ab243f5cded2aa41ee2fa5e1e294d5f8602e7d2e6916bc3a5c43452f2f6190709
          EOF
          npm run build:prod

      - name: Frontend CI
        run: |
          cd frontend
          npm ci
          npm run build:prod

      - name: Deploy to Render
        if: github.ref == 'refs/heads/deploy'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
