name: Deploy Pipeline

on:
  push:
    branches: [deploy, main]
  workflow_dispatch:

jobs:
  all-ci:
    name: Runs Lint, Tests and Build for both frontend and backend and then trigger deploy to render of the latest commits
    runs-on: ubuntu-24.04.1
    steps: 
        - name: Checkout to Branch 
          uses: actions/checkout@v3 

        - name: Checkout to Branch 
          uses: actions/setup-node@v3 
          with:
            node-version: 22.14.0

        - name: Backend CI
          run: |
            cd backend
            npm ci
            npm run build:prod
        
        - name: Frontend CI
          run: |
            cd backend
            npm ci
            npm run build:prod

        - name: Deploy to Render
          run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
